/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package grafico;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Chriss Ramos
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtArchivo1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArchivo2 = new javax.swing.JTextArea();
        lblArchivo1 = new javax.swing.JLabel();
        lblArchivo2 = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        abrirArchivoUno = new javax.swing.JMenuItem();
        abrirArchivoDos = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtArchivo1.setBackground(new java.awt.Color(29, 41, 81));
        txtArchivo1.setColumns(20);
        txtArchivo1.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtArchivo1.setForeground(new java.awt.Color(51, 255, 0));
        txtArchivo1.setRows(5);
        jScrollPane1.setViewportView(txtArchivo1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 200, 340));

        txtArchivo2.setBackground(new java.awt.Color(29, 41, 81));
        txtArchivo2.setColumns(20);
        txtArchivo2.setFont(new java.awt.Font("Monospaced", 0, 18)); // NOI18N
        txtArchivo2.setForeground(new java.awt.Color(102, 255, 51));
        txtArchivo2.setRows(5);
        jScrollPane2.setViewportView(txtArchivo2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 200, 250));

        lblArchivo1.setFont(new java.awt.Font("Lucida Sans Typewriter", 0, 24)); // NOI18N
        lblArchivo1.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo1.setText("Archivo 1");
        getContentPane().add(lblArchivo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblArchivo2.setFont(new java.awt.Font("Lucida Console", 0, 24)); // NOI18N
        lblArchivo2.setForeground(new java.awt.Color(255, 255, 255));
        lblArchivo2.setText("Archivo 2");
        getContentPane().add(lblArchivo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 40));

        fondo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fondo.setForeground(new java.awt.Color(255, 255, 255));
        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo3.jpg"))); // NOI18N
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 920));

        jMenu1.setText("Archivo");

        abrirArchivoUno.setText("Abrir Archivo 1");
        abrirArchivoUno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoUnoActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivoUno);

        abrirArchivoDos.setText("Abrir Archivo 2");
        abrirArchivoDos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                abrirArchivoDosActionPerformed(evt);
            }
        });
        jMenu1.add(abrirArchivoDos);

        jMenuItem3.setText("Salir");
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Juego");

        jMenuItem4.setText("Analizar Archivo 1");
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Analizar Archivo 2");
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Jugar");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Ayuda");

        jMenuItem7.setText("Manual de Usuario");
        jMenu3.add(jMenuItem7);

        jMenuItem8.setText("Manual Tecnico");
        jMenu3.add(jMenuItem8);

        jMenuItem9.setText("Acerca De");
        jMenu3.add(jMenuItem9);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Reportes");

        jMenuItem10.setText("Errores Lexicos");
        jMenu4.add(jMenuItem10);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void abrirArchivoUnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoUnoActionPerformed
        // TODO add your handling code here:
        String aux="";   
        String texto="";
        try
            {
             /**llamamos el metodo que permite cargar la ventana*/
             JFileChooser file=new JFileChooser();
             file.showOpenDialog(this);
             /**abrimos el archivo seleccionado*/
             File abre=file.getSelectedFile();

             /**recorremos el archivo, lo leemos para plasmarlo
             *en el area de texto*/
             if(abre!=null)
             {     
                FileReader archivos=new FileReader(abre);
                BufferedReader lee=new BufferedReader(archivos);
                while((aux=lee.readLine())!=null)
                {
                   texto+= aux+ "\n";
                }
                   lee.close();
              }    
             }
             catch(IOException ex)
             {
               JOptionPane.showMessageDialog(null,ex+"" +
                     "\nNo se ha encontrado el archivo",
                           "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
              }
            txtArchivo1.setText(texto);
        //return texto;//El texto se almacena en el JTextArea
    }//GEN-LAST:event_abrirArchivoUnoActionPerformed

    private void abrirArchivoDosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_abrirArchivoDosActionPerformed
        // TODO add your handling code here:
        String aux="";   
        String texto="";
        try
            {
             /**llamamos el metodo que permite cargar la ventana*/
             JFileChooser file=new JFileChooser();
             file.showOpenDialog(this);
             /**abrimos el archivo seleccionado*/
             File abre=file.getSelectedFile();

             /**recorremos el archivo, lo leemos para plasmarlo
             *en el area de texto*/
             if(abre!=null)
             {     
                FileReader archivos=new FileReader(abre);
                BufferedReader lee=new BufferedReader(archivos);
                while((aux=lee.readLine())!=null)
                {
                   texto+= aux+ "\n";
                }
                   lee.close();
              }    
             }
             catch(IOException ex)
             {
               JOptionPane.showMessageDialog(null,ex+"" +
                     "\nNo se ha encontrado el archivo",
                           "ADVERTENCIA!!!",JOptionPane.WARNING_MESSAGE);
              }
            txtArchivo2.setText(texto);
    }//GEN-LAST:event_abrirArchivoDosActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem abrirArchivoDos;
    private javax.swing.JMenuItem abrirArchivoUno;
    private javax.swing.JLabel fondo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblArchivo1;
    private javax.swing.JLabel lblArchivo2;
    private javax.swing.JTextArea txtArchivo1;
    private javax.swing.JTextArea txtArchivo2;
    // End of variables declaration//GEN-END:variables
}
